# Generated by Django 2.0.7 on 2018-07-04 08:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdminUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(blank=True, max_length=16, null=True)),
                ('password', models.CharField(blank=True, max_length=512, null=True)),
            ],
            options={
                'db_table': 'admin_user',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=16, null=True)),
            ],
            options={
                'db_table': 'brand',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Classification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=16, null=True)),
            ],
            options={
                'db_table': 'classification',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(blank=True, max_length=1024, null=True)),
                ('image', models.CharField(blank=True, max_length=128, null=True)),
                ('create_time', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'comments',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Goods',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=64, null=True)),
                ('c_price', models.FloatField(blank=True, null=True)),
                ('image', models.CharField(blank=True, max_length=128, null=True)),
                ('describtion', models.CharField(blank=True, max_length=128, null=True)),
                ('comments_amount', models.IntegerField(blank=True, null=True)),
                ('sales_number', models.IntegerField(blank=True, null=True)),
                ('source', models.CharField(blank=True, max_length=64, null=True)),
            ],
            options={
                'db_table': 'goods',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='HistoryPrice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.FloatField(blank=True, null=True)),
                ('date', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'history_price',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Hot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(blank=True, max_length=64, null=True)),
                ('count', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'hot',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Subclassification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=16, null=True)),
            ],
            options={
                'db_table': 'subclassification',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(blank=True, max_length=16, null=True)),
                ('passwoed', models.CharField(blank=True, max_length=512, null=True)),
                ('sex', models.IntegerField(blank=True, null=True)),
                ('tel', models.CharField(blank=True, max_length=11, null=True)),
                ('email', models.CharField(blank=True, max_length=32, null=True)),
                ('icon', models.CharField(blank=True, max_length=512, null=True)),
            ],
            options={
                'db_table': 'user',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Focus',
            fields=[
                ('goods', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='app.Goods')),
            ],
            options={
                'db_table': 'focus',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SubclassificationBrand',
            fields=[
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='app.Brand')),
            ],
            options={
                'db_table': 'subclassification_brand',
                'managed': False,
            },
        ),
    ]
